### PR TITLE
experimented with centering the footer buttons

### PR DESCRIPTION
**Pull request by matjlars**
I was just messing around with trying to get those footer buttons centered. I also noticed the 4 non-button links disappear on mobile so I was also messing around with making those appear on mobile.  The 4 links don't wrap great on very small widths, but I'm not sure how small we need to care about.

The one compromise I made is the buttons are a bit wider on desktop but I think it still looks good, what do you think?

This is just a silly experiment, feel free to poo poo on this if you don't like it.  Thanks!

### CODE REVIEW

**Comment by adamfchs** [comment]
Hi Matt,

The four links disappearing on mobile is actually intentional to match the mockups!

The footer buttons being larger on desktop is definitely something you should run by your team!  For theming stuff, we'll start with matching the mockups but after that if you want changes feel free!

**Comment by matjlars** [comment]
oh haha weird. definitely not best practice. ill talk with the team about
both things. thanks!

~Matt

**Comment by adamfchs** [comment]
Its a convention I've some from some designers before—basically providing a little more targeted mobile experience to keep the amount of scroll down an reduce the amount of clutter in space that has limited real estate. Pretty much the same reason we're not showing program images in the teasers on mobile. But...it does mean we're making decisions about what a user wants to see, so I think there is an argument either way.

I did have a thought on the centering of that menu on desktop.  I would think that we could use JS to detect the width of the menu, each menu item in it and their order, and use some math to figure out their placement and detect true center between the buttons from there so keep from having such tight editorial restrictions.  However, we're over time on theming the footer as is so I didn't explore that.

Feel free to do so if you want!  But also remember, you've got the job views, events and restricting profile editing to the user who's profile it is on your plate :)

**Comment by adamfchs** [comment]
In my opinion the easy technical choice (and most future proof) is to remove the button style from Visit and Apply and just center the whole menu in the footer....but not sure that is something that can be sold :)

**Comment by matjlars** [comment]
oh yeah ill bring that up as option 1. great idea.

im waiting on job til a page is styled, waiting on event list til they
decide groups vs tags, and im Active-Procrastinating the profile
permissions until i have maximum brainpower lol. i wanted to throw this
into a PR today because my wife and I spent a long time discussing this
last night so it was fresh in the brain :) she is professor of html/css at
uwec

~Matt

**Comment by adamfchs** [comment]
Fair enough!

Let me know if you can get the button style removal though!!

**Comment by matjlars** [comment]
if u ruled the universe would u stack all 6 on mobile?

~Matt

**Comment by adamfchs** [comment]
I would not. I would actually not have them in the footer at all.

They are all in the main menu and that is generally where a user will look, and the footer is already packed with links and quite tall on mobile.

**Comment by matjlars** [comment]
once again, great idea, thanks for thinking about this with me

~Matt

**Comment by adamfchs** [comment]
Any time!

**Comment by matjlars** [comment]
closing this wild fantasy of having my own agency to make improvements

**Pull request closed without merging**
