### PR TITLE
change livewhale group field

### PR DESCRIPTION
**Pull request by matjlars**
Long story short, I didn't think filtering on group ID was going to work but LiveWhale support found a way to do it.

So this now stores the LiveWhale Group ID instead of the LiveWhale "fullname" field value. So if they rename a group, they won't need to re-select the groups on these events list paragraphs anymore.

### CODE REVIEW

**Comment by adamfchs** [comment]
Hi Matt,

 I merged main into this branch (to keep it current) and added some rough initial theming for this so we can more easily see what we need for events.

I was wondering if you can do the following changes so we can get as close as possible to the structure in the mockups:

- Have the event date shown on each event (not just for the day as a whole).  If possible, we'd want it in this format:  Month (abbreviated), Day (with leading 0), Day of the week (abbreviated). Each one with its own HTML wrapper and a wrapper around the date as a whole (so I can make the calendar card date format work).  Do not have the date be an h4–just a regular div.
- Have an individual wrapper div for each event in the day.
- Get the image in as a 332x332px image
- Do not have the title be an H4-just a regular div
- Move the time underneath the title and summary and don't have a colon after it.
- The mockups don't show an 'until' date but I think that's helpful so let's keep it.
- Add the location at the bottom of the event data

Live way adds a bunch of empty date divs after the first date div with 3 events. Anyway we can clean that up.  Ideally, I think we'd just pull in the first three upcoming events no matter their day and thats it.

**Comment by matjlars** [comment]
Ok I believe I have all of this done except the date-component wrappers. I have a ticket in to livewhale to see if that is possible

**Comment by matjlars** [comment]
Ok this should be ready for styling Adam!

**Comment by adamfchs** [comment]
Awesome work Matt!  I believe that is everything I need. I'll take it from here.

**Pull request merged**
