### PR TITLE
external articles paragraph

### PR DESCRIPTION
**Pull request by matjlars**
This adds a paragraph called External Articles that is just a simple list of linkable image tiles.

### CODE REVIEW

**Comment by adamfchs** [comment]
Hi Matt!

Great start on this!  I think we need a few small changes for though:

- All of the paragraphs that have child paragraphs have a particular form display setup on their paragraphs field. You can see an example of the settings on the accordions, select type, etc parent paragraphs. Please update the form display settings for the  paragraphs field on external articles to match. This helps provide a minimal and consistent experience to the editors.
- Should the articles field on the parent paragraph be limited to three as Mackenzie noted in basecamp?
- All paragraphs have a Preview rendered display mode. This is because we use preview as the closed display mode on all paragraphs fields (on content types and parent paragraphs) to cut down on the clutter on node forms. Please set a preview display for the parent external article paragraph that renders the child as preview (otherwise the preview view mode you set on the child won't be used).
- The help text for the image field on the child paragraph has information about the CTA paragraph in it. It should probably be specific to just the external article paragraph. The optimal image size is also much larger than what will be rendered as the 393x221 image you have set. The optimal image size help text in image fields always calls out the largest rendered size for the field. If you're using the 393x221 style, the largest size would be 786x442 (retina 2x).
- We typically use a headline or title (plain text field of some kind) and use the link field to link that title. We do this so that editors can enter more than the 80 characters that Drupal trims link text to and because editors are used to entering the 'names' of things. I'd recommend keeping that convention for the child external articel paragraph rather than just having them type link text and using that for the headline. If you do stick with just a link field, it should not be trimmed to 80px when rendered.
- Since these are always meant to be external articles, I'm wondering if the link field should only allow external links?
- Should there be an additional plain long text field
- Permissions need to be set for both paragraphs.
- Please move the external article paragraph into alphabetical order on the general page sections field (and any other content type its used on). Keeping the paragraphs in order helps the editors find them quicker.
- There should also be an icon for the external article parent paragraph. We get all of the paragraph icons from Material: https://fonts.google.com/icons?icon.style=Filled&icon.set=Material+Icons. Just find one that makes sense, download the svg and add it via the citizen_custom module.
- As I noted in basecamp, you'll want to style these like the Stories & Video paragraph. You can add an an example of that to a page along with this widget to visually compare and you can like copy and paste the applicable theming for things like the text from the story teaser teaser theming.
- Since we don't use the convention of making the image and the text a link anywhere else on the site, we should not do that here either. Only the text should be a link. You'll need to have a span inside the <a> so you can do the dotted underline when on hover (see story teaser).
- I'm think these should have the same animation as the stories and video widget so the image fades in when a user scrolls to them. You can see an example of this on the stories & video widget.  You'll want to copy the story & video list js file and a create a new library (see libraries.yml) that attaches it to a Twig template for the parent paragraph.

**Comment by matjlars** [comment]
Ok thanks very much for all the feedback!

**Comment by matjlars** [comment]
Ok I finished going through all the feedback.

1. Done
1. No. She did not say to limit it to 3.
1. Done
1. Done
1. Done. (I went with your second option of using the link text field for the link text)
1. I considered restricting it to external too but decided against it because it is not hurting anything that I can think of to allow linking to internal things, and I know there will be someone at some point who will want to.
1. No? I'm not a hundo on what you mean.
1. Done
1. Done
1. Done
1. Done
1. Done
1. Done

**Comment by matjlars** [comment]
@adamfchs let me know whether you plan on QAing this one again. If not I can just merge it in. Thanks!

**Pull request merged**
