### PR TITLE
attempt to make masonry use image styles

### PR DESCRIPTION
**Pull request by matjlars**
I need a QA check on this one. This is a potential fix for [bugherd 117](https://www.bugherd.com/projects/391209/tasks/177)

I think this looks good but when I try to view the test page: http://uwec.docksal.site/academics/academic-experience/study-away

The gallery is blank, like the photos aren't loading. It looks like the img tags have the right src values though, so maybe it's just an issue with the image proxy thingy?

### CODE REVIEW

**Comment by adamfchs** [comment]
@matjlars The images not rendering is because of stage file proxy. If an image has not used the style you're trying to use on the live site there will not be a matching version for stage file proxy to pull in locally.  For new image style setups I test by disabling stage file proxy and uploading new images.

The image styles you set are working, but the masonry looks really weird with them. See attached screenshot. 
screencapture-uwec-docksal-site-gallery-test-2024-08-22-14_57_22
I now dimly remember that being why we went without image styles.  I think its because the masonry script has issues when images are the same size.

I'm wondering there is another option to explore though.  Some thoughts:
- Maybe try to set up two to or three more styles that can be added to images in the array somehow tied to factors of their initial array position.  Something like every 4n+1 image uses style x, 4n+2 style y, 4n+3 style z, etc.  That would give masonry more to choose from when building the gallery.
- Maybe there is a way to render images using their default aspect ratios but as a smaller file size? Never tried that in Twig or a preprocess before could be something to investigate.
- Maybe try a different masonry script or a purely CSS approach potentially using CSS grid?

**Comment by matjlars** [comment]
Ok thanks for all the detailed information and suggestions! I will do some research and consult The Team. A pure css approach sounds really nice to me, if I can figure out a nice way to do it while still keeping the "random"ish look to it. Thanks again!

**Comment by adamfchs** [comment]
Yeah, for a pure CSS approach it could look something like this:

- Plan on theming galleries with up to 20 images just to cover all bases.
- Come up with 3 or 4 css layouts so you can theme it logically but it can still be random (ish).
- Use relative and absolution positioning to place the images using different sizes to get the random feel.  The Twig image shuffle will also help with the randomness. You can also rearrange at different screen sizes.
- Add a random number class the twig template at the gallery wrapper level with a max of 3 or 4 (whatever matches the amount of layouts you do).  That way the gallery will randomly get a class that matches one of the 3 (or 4) layouts you created to determine which is used.

A lot of work, but theoretically doable while still keeping all the image style performance and reducing the JS performance hit.

**Comment by matjlars** [comment]
Ok yeah I see, that could be interesting!  I'm hoping to talk The Team into a look that will be easy to make work for any amount of images. I don't know if there is any history or any specifics on this thing for UWEC but I'm reading up on it now and it looks like classic "masonry" is just fixed width columns with consistent vertical spacing between items, which seems pretty easy to do with pure css, as long as that is acceptable to The Team. On some blog posts they are saying it's tricky to order the items but in this case, the order does not matter, in fact it is already shuffled, so we've got that going for us.

**Comment by matjlars** [comment]
This looks like pretty much exactly what I was thinking: https://www.freecodecamp.org/news/how-to-create-a-mansory-layout-using-html-and-css/

**Comment by adamfchs** [comment]
Gotcha.  Not sure how well that would work with horizontal images, but you could probably come up with a horizontal version or maybe have some images horizontal, some vertical, some square, etc.

**Comment by matjlars** [comment]
Yeah you are right, horizontal images would be small. That's not ideal. I like your idea to have a few different layouts that it randomly selects from. I wonder if there is a way to read the aspect ratio and/or pixel dimensions of the images in the twig template or in preprocess so I could maybe select a layout depending on the first x images being horizontal or vertical? Or I could, like, fill specific slots with horizontal images, at least. Do you know if that is possible in twig or preprocess?

**Comment by adamfchs** [comment]
I know you can read the size in Twig. It would be something like field_image.entity.field_media_image.entity.width (use dd() to get the actual path but it should be something like that). Never tried in proprocess the data structure should be the same. 

If we go the CSS route you should be setting responsive image styles on these so you'll have aspect ratio and dimensions info from the image style.

**Comment by matjlars** [comment]
Ok yep there is "width" and "height" available in twig on those. Ok I'm going to be pondering this and I'm going to discuss with The Team on Tuesday during our weekly meeting. Thanks for helping brainstorm Adam!

**Comment by adamfchs** [comment]
For sure!  Have a good weekend

**Pull request closed without merging**
