### PR TITLE
home page video hero redesign

### PR DESCRIPTION
**Pull request by matjlars**
This changes the video hero design based on this basecamp: https://basecamp.com/1970294/projects/19048586/messages/108808862

Adam, please QA this one. Even though I'm pretty sure all the CSS changes were specifically scoped to the video hero type, it'd be a good idea to test the other types anyway.

## Some notes

This also updates the pause/play video logic to use localStorage instead of cookies. I have not updated the play/pause animation logic yet.

I did a small refactor of admin-side hero fields show/hide js.

I removed autoload on video and instead play it from js based on a min screen width, so the video doesn't even begin to load on mobile. It appears to work but I've never done that before so let me know if you know a better way.

For the text beneath the h1, I used the existing page Intro field (machine name "body") just like the other hero types.

For the button(s), I used the already existing hero links field. So I didn't actually end up needing to add any additional fields for anything.

I'm eyeballing the gradient colors/stops/angles because I never heard back from Kristin when I asked for info on the gradients so that may need a bit of tweaking.

Thanks Adam!

### CODE REVIEW

**Comment by adamfchs** [comment]
Hi Matt!  Nice first run at this but I think we need a few changes. 

One of the things we talked about what adding a new video title field so that the actual node title could be 'home' so it can be consistent and easily found on the admin side. Did your team decide against that?

You mentioned that you are using JS to only play the video at a certain screensize. That does not appear to be working. Testing both in a small browser window and on a Browser Stack iPhone 16, the video plays automatically on mobile. 

There is also weirdness that happens at larger screen sizes when the video is paused and the page is reloaded (or you go to another page and then back to the home page (see attached screenshot).  The video does not load at full width.
Screenshot 2024-10-31 at 11 50 54 AM

If the video is supposed to be full width, we shouldn't also be loading the background image anymore. Its weird seeing a flash of the background image before the video kicks in and its not great for performance. I think we can just go with a solid background color before the video loads.

One of the other things we talked about in the meeting was to use a static image on mobile—rather than just not auto playing the video. I think static image could also help with some of the layout issues on mobile (see next paragraph).

The way things are arranged on mobile seems a little off.  Depending on the height of the user's device, the header can appear to get chopped in half because of the background not going full height (see attached screenshot).
Screenshot 2024-10-31 at 11 22 42 AM
  The video title has a large gap between it and the intro text/button if they are used. It feels separated from the other text elements. The button gets chopped off at the bottom no matter the mobile height (see attached screenshot). 
Screenshot 2024-10-31 at 11 28 29 AM

At larger screen sizes, I think the text should be locked to the max width that we do on the image background (and stories) heroes. Because its locked to the left edge right now on large screens it gets a weird offset from the header content and the rest of the content on the page.  Locking it to 1320 so it lines up with the left edge of the nav could also work.

There should be a hover effect on the video play/pause button.  I'm thinking underlining the text and changing the colors of the text and icon from white to gold or maybe changing the opacity to .7 or something?

It seems a little weird to me that the play/pause icon doesn't stay snug with the text when the text is changed to play. There is a large gap between the play text and the icon which seems odd.

The hover effect on the outline button in the hero text changes it to a solid navy—which is difficult to make out because of the darkness of the video and the gradient. I'm thinking we should change that be solid white on hover/focus. 

When more than one link is added they are almost touching and they overlap a bit when the hover breathe effect happens.

I'm thinking we should animate the gold stripes in from the right the way we animate other decorative elements.

I get the logic behind using the page intro field for the descriptive text, but it creates an odd editorial experience. You enter the video and the link(s) when scroll down to the page title and then the intro which appear above the links. But if you enter a subtitle between the title and intro it doesn't appear anywhere? Some of that weirdness is likely there form before but it we change to a dedicated video title field, I think we can also switch to a dedicated description field in the video hero and solve all of it.

**Comment by matjlars** [comment]
I remember us discussing the page title and I couldn't remember where we landed. I asked the other web team folks but nobody responded. I'll add a new field because I agree that will be better.

Thanks a million Adam!

**Comment by matjlars** [comment]
task list for myself

- [ ] new field: video title, instead of page title
- [ ] new field: video description, instead of body
- [ ] reconsider video autoload logic (higher screen width? user agent detection instead?)
- [ ] video not loading at full width when already paused for adam
- [ ] make sure static image is working on mobile
- [ ] don't load static image on not-mobile
- [ ] make the static image go all the way up to the top (on mobile)
- [ ] weird gap issue after video title (see adam's screenshot)
- [ ] try max width 1320 on inner text
- [ ] hover effect on play/pause (underline and opacity .7)
- [ ] link button white background on hover
- [ ] scoot multiple link buttons apart a bit

**Comment by matjlars** [comment]
Hi @adamfchs I got almost everything fixed. I just want to ask two questions before I finish the last things.

How would you decide on whether to show the image version vs the video version?  I am going by screen width (min-width:600px), but it looks like the iPhone 16 you tested with has a screen width of over 1100px!  Should I move the width cutoff point to like, 1200px?? That seems too wide, like it wouldn't display the video when it should, maybe. So yeah, how would you differentiate between devices that should play the video vs not play the video?

By "static image" are you referring to the video poster, or should I use the background image field, or something else?

Thanks again!

**Comment by adamfchs** [comment]
@matjlars I think the iphone 16 pixels you a referencing are not CSS pixels.  The 16 I testing was still showing the usual mobile styles which wouldn't be the case if those 1100px were CSS pixels.  For the image detection, yeah, I would use screen width and whatever existing breakpoint we have near 600 sounds good!

For the static image, yeah, that would be the video poster!

**Comment by matjlars** [comment]
Ok sounds good. Thanks!

**Comment by matjlars** [comment]
Ok I think it's all good!   I'm merging this so I can deploy to the test env.

**Pull request merged**
